services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: darren24
      POSTGRES_DB: wuzzapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  development:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "9229:9229"
      - "9230:9230"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    command: npm run dev:debug

volumes:
  db_data:
